sudo: required
services:
  - docker

before_install: 
  - docker build -t tamirraz/docker-k8s -f Dockerfile.dev .

script: 
  - docker run -e CI=true tamirraz/docker-k8s npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-730335493087"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"   
